package generator

const projectGoModTemplate = `module {{.ModulePath}}

go 1.22

{{if .UsesGin}}require github.com/gin-gonic/gin v1.10.0
{{end}}
`

const envTemplate = `APP_ENV=local
HTTP_ADDR=:8080
`

const makefileTemplate = `.PHONY: run test tidy

run:
	go run ./cmd/{{.Name}}

test:
	go test ./...

tidy:
	go mod tidy
`

const projectReadmeTemplate = `# {{.Name}}

Generated by GoCraft.

Framework: {{.Router}}

## Run

` + "```sh" + `
make run
` + "```" + `

The service starts an HTTP server on ` + "`HTTP_ADDR`" + ` and exposes:

- ` + "`GET /health`" + `

## Structure

- ` + "`cmd/{{.Name}}`" + ` - application entrypoint
- ` + "`internal/handler`" + ` - HTTP handlers
- ` + "`internal/service`" + ` - application services
- ` + "`internal/repository`" + ` - data access layer
- ` + "`internal/models`" + ` - domain models
- ` + "`internal/config`" + ` - environment configuration
`

const netHTTPMainTemplate = `package main

import (
	"log/slog"
	"net/http"
	"os"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := http.ListenAndServe(cfg.HTTPAddr, mux); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const ginMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	router := gin.Default()
	router.GET("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := router.Run(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const configTemplate = `package config

import "os"

type Config struct {
	AppEnv   string
	HTTPAddr string
}

func Load() Config {
	return Config{
		AppEnv:   getEnv("APP_ENV", "local"),
		HTTPAddr: getEnv("HTTP_ADDR", ":8080"),
	}
}

func getEnv(key, fallback string) string {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return value
}
`

const netHTTPHealthHandlerTemplate = `package handler

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(h.service.Check(r.Context())); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`

const ginHealthHandlerTemplate = `package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(c *gin.Context) {
	c.JSON(http.StatusOK, h.service.Check(c.Request.Context()))
}
`

const healthServiceTemplate = `package service

import (
	"context"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/repository"
)

type HealthService struct {
	repository *repository.HealthRepository
}

func NewHealthService(repository *repository.HealthRepository) *HealthService {
	return &HealthService{repository: repository}
}

func (s *HealthService) Check(ctx context.Context) models.HealthStatus {
	return s.repository.Status(ctx)
}
`

const healthRepositoryTemplate = `package repository

import (
	"context"
	"time"

	"{{.ModulePath}}/internal/models"
)

type HealthRepository struct{}

func NewHealthRepository() *HealthRepository {
	return &HealthRepository{}
}

func (r *HealthRepository) Status(ctx context.Context) models.HealthStatus {
	return models.HealthStatus{
		Status: "ok",
		Time:   time.Now().UTC(),
	}
}
`

const healthModelTemplate = `package models

import "time"

type HealthStatus struct {
	Status string    ` + "`json:\"status\"`" + `
	Time   time.Time ` + "`json:\"time\"`" + `
}
`

const configExampleTemplate = `app:
  env: local
http:
  addr: :8080
`

const resourceModelTemplate = `package models

type {{.TypeName}} struct {
	ID string ` + "`json:\"id\"`" + `
}
`

const resourceRepositoryTemplate = `package repository

import (
	"context"

	"{{.ModulePath}}/internal/models"
)

type {{.TypeName}}Repository interface {
	Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error)
	FindByID(ctx context.Context, id string) (models.{{.TypeName}}, error)
}

type InMemory{{.TypeName}}Repository struct {
	items map[string]models.{{.TypeName}}
}

func NewInMemory{{.TypeName}}Repository() *InMemory{{.TypeName}}Repository {
	return &InMemory{{.TypeName}}Repository{items: make(map[string]models.{{.TypeName}})}
}

func (r *InMemory{{.TypeName}}Repository) Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error) {
	r.items[item.ID] = item
	return item, nil
}

func (r *InMemory{{.TypeName}}Repository) FindByID(ctx context.Context, id string) (models.{{.TypeName}}, error) {
	return r.items[id], nil
}
`

const resourceServiceTemplate = `package service

import (
	"context"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/repository"
)

type {{.TypeName}}Service struct {
	repository repository.{{.TypeName}}Repository
}

func New{{.TypeName}}Service(repository repository.{{.TypeName}}Repository) *{{.TypeName}}Service {
	return &{{.TypeName}}Service{repository: repository}
}

func (s *{{.TypeName}}Service) Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error) {
	return s.repository.Create(ctx, item)
}
`

const resourceHandlerTemplate = `package handler

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/service"
)

type {{.TypeName}}Handler struct {
	service *service.{{.TypeName}}Service
}

func New{{.TypeName}}Handler(service *service.{{.TypeName}}Service) *{{.TypeName}}Handler {
	return &{{.TypeName}}Handler{service: service}
}

func (h *{{.TypeName}}Handler) Create(w http.ResponseWriter, r *http.Request) {
	var input models.{{.TypeName}}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	created, err := h.service.Create(r.Context(), input)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(created)
}
`
