package generator

const projectGoModTemplate = `module {{.ModulePath}}

go 1.22

{{if .HasDeps}}require (
{{if .UsesGin}}	github.com/gin-gonic/gin v1.10.0
{{end}}{{if .UsesChi}}	github.com/go-chi/chi/v5 v5.1.0
{{end}}{{if .UsesFiber}}	github.com/gofiber/fiber/v2 v2.52.5
{{end}}{{if .UsesEcho}}	github.com/labstack/echo/v4 v4.12.0
{{end}}{{if .UsesPostgres}}	github.com/jackc/pgx/v5 v5.7.1
{{end}})
{{end}}
`

const envTemplate = `APP_ENV=local
HTTP_ADDR=:8080
{{if .UsesPostgres}}DATABASE_URL=postgres://postgres:postgres@localhost:5432/{{.PackageName}}?sslmode=disable
{{end}}
`

const makefileTemplate = `.PHONY: run test tidy
{{if .UsesPostgres}}.PHONY: db-up db-down migrate-up migrate-down
{{end}}

run:
	go run ./cmd/{{.Name}}

test:
	go test ./...

tidy:
	go mod tidy
{{if .UsesPostgres}}
db-up:
	docker compose up -d postgres

db-down:
	docker compose down

migrate-up:
	@echo "Apply migrations with your migration tool of choice from ./migrations"

migrate-down:
	@echo "Rollback migrations with your migration tool of choice from ./migrations"
{{end}}
`

const projectReadmeTemplate = `# {{.Name}}

Generated by GoCraft.

Framework: {{.Router}}

Architecture: {{.Arch}}

## Run

` + "```sh" + `
make run
` + "```" + `

The service starts an HTTP server on ` + "`HTTP_ADDR`" + ` and exposes:

- ` + "`GET /health`" + `
{{if .UsesPostgres}}
## Database

This project includes PostgreSQL support through ` + "`database/sql`" + ` and ` + "`github.com/jackc/pgx/v5/stdlib`" + `.

Start PostgreSQL:

` + "```sh" + `
make db-up
` + "```" + `

Connection string is configured with ` + "`DATABASE_URL`" + ` in ` + "`.env`" + `.
{{end}}

## Structure

{{if .IsClean}}
- ` + "`cmd/{{.Name}}`" + ` - application entrypoint
- ` + "`internal/domain`" + ` - enterprise/domain models
- ` + "`internal/usecase`" + ` - application use cases and ports
- ` + "`internal/interface/http`" + ` - HTTP delivery layer
- ` + "`internal/infrastructure/repository`" + ` - infrastructure adapters
- ` + "`internal/config`" + ` - environment configuration
{{else}}
- ` + "`cmd/{{.Name}}`" + ` - application entrypoint
- ` + "`internal/handler`" + ` - HTTP handlers
- ` + "`internal/service`" + ` - application services
- ` + "`internal/repository`" + ` - data access layer
- ` + "`internal/models`" + ` - domain models
- ` + "`internal/config`" + ` - environment configuration
{{end}}

## Next Steps

` + "```sh" + `
make run
make test
` + "```" + `
`

const postgresTemplate = `package database

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func Connect(ctx context.Context, databaseURL string) (*sql.DB, error) {
	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open postgres: %w", err)
	}

	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(time.Hour)

	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}

	return db, nil
}
`

const dockerComposeTemplate = `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: {{.PackageName}}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`

const migrationUpTemplate = `-- Add initial database schema here.
`

const migrationDownTemplate = `-- Drop initial database schema here.
`

const netHTTPMainTemplate = `package main

import (
	"log/slog"
	"net/http"
	"os"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := http.ListenAndServe(cfg.HTTPAddr, mux); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const ginMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	router := gin.Default()
	router.GET("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := router.Run(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const chiMainTemplate = `package main

import (
	"log/slog"
	"net/http"
	"os"

	"github.com/go-chi/chi/v5"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	router := chi.NewRouter()
	router.Get("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := http.ListenAndServe(cfg.HTTPAddr, router); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const fiberMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/gofiber/fiber/v2"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	app := fiber.New()
	app.Get("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := app.Listen(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const echoMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/labstack/echo/v4"

	"{{.ModulePath}}/internal/config"
	"{{.ModulePath}}/internal/handler"
	"{{.ModulePath}}/internal/repository"
	"{{.ModulePath}}/internal/service"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)

	app := echo.New()
	app.GET("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := app.Start(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const configTemplate = `package config

import "os"

type Config struct {
	AppEnv   string
	HTTPAddr string
{{if .UsesPostgres}}	DatabaseURL string
{{end}}
}

func Load() Config {
	return Config{
		AppEnv:   getEnv("APP_ENV", "local"),
		HTTPAddr: getEnv("HTTP_ADDR", ":8080"),
{{if .UsesPostgres}}		DatabaseURL: getEnv("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/{{.PackageName}}?sslmode=disable"),
{{end}}
	}
}

func getEnv(key, fallback string) string {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return value
}
`

const cleanNetHTTPMainTemplate = `package main

import (
	"log/slog"
	"net/http"
	"os"

	"{{.ModulePath}}/internal/config"
	httpapi "{{.ModulePath}}/internal/interface/http"
	"{{.ModulePath}}/internal/infrastructure/repository"
	"{{.ModulePath}}/internal/usecase"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthUsecase := usecase.NewHealthUsecase(healthRepository)
	healthHandler := httpapi.NewHealthHandler(healthUsecase)

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := http.ListenAndServe(cfg.HTTPAddr, mux); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const cleanGinMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/config"
	httpapi "{{.ModulePath}}/internal/interface/http"
	"{{.ModulePath}}/internal/infrastructure/repository"
	"{{.ModulePath}}/internal/usecase"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthUsecase := usecase.NewHealthUsecase(healthRepository)
	healthHandler := httpapi.NewHealthHandler(healthUsecase)

	router := gin.Default()
	router.GET("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := router.Run(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const cleanChiMainTemplate = `package main

import (
	"log/slog"
	"net/http"
	"os"

	"github.com/go-chi/chi/v5"

	"{{.ModulePath}}/internal/config"
	httpapi "{{.ModulePath}}/internal/interface/http"
	"{{.ModulePath}}/internal/infrastructure/repository"
	"{{.ModulePath}}/internal/usecase"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthUsecase := usecase.NewHealthUsecase(healthRepository)
	healthHandler := httpapi.NewHealthHandler(healthUsecase)

	router := chi.NewRouter()
	router.Get("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := http.ListenAndServe(cfg.HTTPAddr, router); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const cleanFiberMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/gofiber/fiber/v2"

	"{{.ModulePath}}/internal/config"
	httpapi "{{.ModulePath}}/internal/interface/http"
	"{{.ModulePath}}/internal/infrastructure/repository"
	"{{.ModulePath}}/internal/usecase"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthUsecase := usecase.NewHealthUsecase(healthRepository)
	healthHandler := httpapi.NewHealthHandler(healthUsecase)

	app := fiber.New()
	app.Get("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := app.Listen(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const cleanEchoMainTemplate = `package main

import (
	"log/slog"
	"os"

	"github.com/labstack/echo/v4"

	"{{.ModulePath}}/internal/config"
	httpapi "{{.ModulePath}}/internal/interface/http"
	"{{.ModulePath}}/internal/infrastructure/repository"
	"{{.ModulePath}}/internal/usecase"
)

func main() {
	cfg := config.Load()
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	healthRepository := repository.NewHealthRepository()
	healthUsecase := usecase.NewHealthUsecase(healthRepository)
	healthHandler := httpapi.NewHealthHandler(healthUsecase)

	app := echo.New()
	app.GET("/health", healthHandler.Check)

	logger.Info("starting server", "addr", cfg.HTTPAddr)
	if err := app.Start(cfg.HTTPAddr); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
`

const netHTTPHealthHandlerTemplate = `package handler

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(h.service.Check(r.Context())); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`

const cleanNetHTTPHealthHandlerTemplate = `package httpapi

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/usecase"
)

type HealthHandler struct {
	usecase *usecase.HealthUsecase
}

func NewHealthHandler(usecase *usecase.HealthUsecase) *HealthHandler {
	return &HealthHandler{usecase: usecase}
}

func (h *HealthHandler) Check(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(h.usecase.Check(r.Context())); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`

const ginHealthHandlerTemplate = `package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(c *gin.Context) {
	c.JSON(http.StatusOK, h.service.Check(c.Request.Context()))
}
`

const cleanGinHealthHandlerTemplate = `package httpapi

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"{{.ModulePath}}/internal/usecase"
)

type HealthHandler struct {
	usecase *usecase.HealthUsecase
}

func NewHealthHandler(usecase *usecase.HealthUsecase) *HealthHandler {
	return &HealthHandler{usecase: usecase}
}

func (h *HealthHandler) Check(c *gin.Context) {
	c.JSON(http.StatusOK, h.usecase.Check(c.Request.Context()))
}
`

const fiberHealthHandlerTemplate = `package handler

import (
	"context"

	"github.com/gofiber/fiber/v2"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(c *fiber.Ctx) error {
	return c.JSON(h.service.Check(context.Background()))
}
`

const cleanFiberHealthHandlerTemplate = `package httpapi

import (
	"context"

	"github.com/gofiber/fiber/v2"

	"{{.ModulePath}}/internal/usecase"
)

type HealthHandler struct {
	usecase *usecase.HealthUsecase
}

func NewHealthHandler(usecase *usecase.HealthUsecase) *HealthHandler {
	return &HealthHandler{usecase: usecase}
}

func (h *HealthHandler) Check(c *fiber.Ctx) error {
	return c.JSON(h.usecase.Check(context.Background()))
}
`

const echoHealthHandlerTemplate = `package handler

import (
	"net/http"

	"github.com/labstack/echo/v4"

	"{{.ModulePath}}/internal/service"
)

type HealthHandler struct {
	service *service.HealthService
}

func NewHealthHandler(service *service.HealthService) *HealthHandler {
	return &HealthHandler{service: service}
}

func (h *HealthHandler) Check(c echo.Context) error {
	return c.JSON(http.StatusOK, h.service.Check(c.Request().Context()))
}
`

const cleanEchoHealthHandlerTemplate = `package httpapi

import (
	"net/http"

	"github.com/labstack/echo/v4"

	"{{.ModulePath}}/internal/usecase"
)

type HealthHandler struct {
	usecase *usecase.HealthUsecase
}

func NewHealthHandler(usecase *usecase.HealthUsecase) *HealthHandler {
	return &HealthHandler{usecase: usecase}
}

func (h *HealthHandler) Check(c echo.Context) error {
	return c.JSON(http.StatusOK, h.usecase.Check(c.Request().Context()))
}
`

const cleanHealthDomainTemplate = `package domain

import "time"

type HealthStatus struct {
	Status string    ` + "`json:\"status\"`" + `
	Time   time.Time ` + "`json:\"time\"`" + `
}
`

const cleanHealthUsecaseTemplate = `package usecase

import (
	"context"

	"{{.ModulePath}}/internal/domain"
)

type HealthRepository interface {
	Status(ctx context.Context) domain.HealthStatus
}

type HealthUsecase struct {
	repository HealthRepository
}

func NewHealthUsecase(repository HealthRepository) *HealthUsecase {
	return &HealthUsecase{repository: repository}
}

func (u *HealthUsecase) Check(ctx context.Context) domain.HealthStatus {
	return u.repository.Status(ctx)
}
`

const cleanHealthRepositoryTemplate = `package repository

import (
	"context"
	"time"

	"{{.ModulePath}}/internal/domain"
)

type HealthRepository struct{}

func NewHealthRepository() *HealthRepository {
	return &HealthRepository{}
}

func (r *HealthRepository) Status(ctx context.Context) domain.HealthStatus {
	return domain.HealthStatus{
		Status: "ok",
		Time:   time.Now().UTC(),
	}
}
`

const healthServiceTemplate = `package service

import (
	"context"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/repository"
)

type HealthService struct {
	repository *repository.HealthRepository
}

func NewHealthService(repository *repository.HealthRepository) *HealthService {
	return &HealthService{repository: repository}
}

func (s *HealthService) Check(ctx context.Context) models.HealthStatus {
	return s.repository.Status(ctx)
}
`

const healthRepositoryTemplate = `package repository

import (
	"context"
	"time"

	"{{.ModulePath}}/internal/models"
)

type HealthRepository struct{}

func NewHealthRepository() *HealthRepository {
	return &HealthRepository{}
}

func (r *HealthRepository) Status(ctx context.Context) models.HealthStatus {
	return models.HealthStatus{
		Status: "ok",
		Time:   time.Now().UTC(),
	}
}
`

const healthModelTemplate = `package models

import "time"

type HealthStatus struct {
	Status string    ` + "`json:\"status\"`" + `
	Time   time.Time ` + "`json:\"time\"`" + `
}
`

const configExampleTemplate = `app:
  env: local
http:
  addr: :8080
`

const resourceModelTemplate = `package models

type {{.TypeName}} struct {
	ID string ` + "`json:\"id\"`" + `
}
`

const resourceRepositoryTemplate = `package repository

import (
	"context"

	"{{.ModulePath}}/internal/models"
)

type {{.TypeName}}Repository interface {
	Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error)
	FindByID(ctx context.Context, id string) (models.{{.TypeName}}, error)
}

type InMemory{{.TypeName}}Repository struct {
	items map[string]models.{{.TypeName}}
}

func NewInMemory{{.TypeName}}Repository() *InMemory{{.TypeName}}Repository {
	return &InMemory{{.TypeName}}Repository{items: make(map[string]models.{{.TypeName}})}
}

func (r *InMemory{{.TypeName}}Repository) Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error) {
	r.items[item.ID] = item
	return item, nil
}

func (r *InMemory{{.TypeName}}Repository) FindByID(ctx context.Context, id string) (models.{{.TypeName}}, error) {
	return r.items[id], nil
}
`

const resourceServiceTemplate = `package service

import (
	"context"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/repository"
)

type {{.TypeName}}Service struct {
	repository repository.{{.TypeName}}Repository
}

func New{{.TypeName}}Service(repository repository.{{.TypeName}}Repository) *{{.TypeName}}Service {
	return &{{.TypeName}}Service{repository: repository}
}

func (s *{{.TypeName}}Service) Create(ctx context.Context, item models.{{.TypeName}}) (models.{{.TypeName}}, error) {
	return s.repository.Create(ctx, item)
}
`

const resourceHandlerTemplate = `package handler

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/models"
	"{{.ModulePath}}/internal/service"
)

type {{.TypeName}}Handler struct {
	service *service.{{.TypeName}}Service
}

func New{{.TypeName}}Handler(service *service.{{.TypeName}}Service) *{{.TypeName}}Handler {
	return &{{.TypeName}}Handler{service: service}
}

func (h *{{.TypeName}}Handler) Create(w http.ResponseWriter, r *http.Request) {
	var input models.{{.TypeName}}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	created, err := h.service.Create(r.Context(), input)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(created)
}
`

const cleanResourceDomainTemplate = `package domain

type {{.TypeName}} struct {
	ID string ` + "`json:\"id\"`" + `
}
`

const cleanResourceUsecaseTemplate = `package usecase

import (
	"context"

	"{{.ModulePath}}/internal/domain"
)

type {{.TypeName}}Repository interface {
	Create(ctx context.Context, item domain.{{.TypeName}}) (domain.{{.TypeName}}, error)
	FindByID(ctx context.Context, id string) (domain.{{.TypeName}}, error)
}

type {{.TypeName}}Usecase struct {
	repository {{.TypeName}}Repository
}

func New{{.TypeName}}Usecase(repository {{.TypeName}}Repository) *{{.TypeName}}Usecase {
	return &{{.TypeName}}Usecase{repository: repository}
}

func (u *{{.TypeName}}Usecase) Create(ctx context.Context, item domain.{{.TypeName}}) (domain.{{.TypeName}}, error) {
	return u.repository.Create(ctx, item)
}
`

const cleanResourceRepositoryTemplate = `package repository

import (
	"context"

	"{{.ModulePath}}/internal/domain"
)

type InMemory{{.TypeName}}Repository struct {
	items map[string]domain.{{.TypeName}}
}

func NewInMemory{{.TypeName}}Repository() *InMemory{{.TypeName}}Repository {
	return &InMemory{{.TypeName}}Repository{items: make(map[string]domain.{{.TypeName}})}
}

func (r *InMemory{{.TypeName}}Repository) Create(ctx context.Context, item domain.{{.TypeName}}) (domain.{{.TypeName}}, error) {
	r.items[item.ID] = item
	return item, nil
}

func (r *InMemory{{.TypeName}}Repository) FindByID(ctx context.Context, id string) (domain.{{.TypeName}}, error) {
	return r.items[id], nil
}
`

const cleanResourceHandlerTemplate = `package httpapi

import (
	"encoding/json"
	"net/http"

	"{{.ModulePath}}/internal/domain"
	"{{.ModulePath}}/internal/usecase"
)

type {{.TypeName}}Handler struct {
	usecase *usecase.{{.TypeName}}Usecase
}

func New{{.TypeName}}Handler(usecase *usecase.{{.TypeName}}Usecase) *{{.TypeName}}Handler {
	return &{{.TypeName}}Handler{usecase: usecase}
}

func (h *{{.TypeName}}Handler) Create(w http.ResponseWriter, r *http.Request) {
	var input domain.{{.TypeName}}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	created, err := h.usecase.Create(r.Context(), input)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(created)
}
`
